---
ida_version: "77"
ida_installer: "idafree{{ ida_version }}_linux.run"

cutter_version: "v2.0.5"
cutter_binary: "Cutter-{{ cutter_version }}-x64.Linux.AppImage"

re_tool_sources:
  - "https://out7.hex-rays.com/files/{{ ida_installer }}"
  - "https://github.com/rizinorg/cutter/releases/download/{{ cutter_version }}/{{ cutter_binary }}"

pwntool_dependencies:
  - python3
  - python3-pip
  - python3-dev
  - git
  - libssl-dev
  - libffi-dev
  - build-essential

python_bindings:
  - capstone
  - unicorn
  - keystone-engine
  - ropper
  - pwntools

re_tools:
  - ghidra
