---
re_frameworks:
  - https://out7.hex-rays.com/files/idafree70_linux.run
  - https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.1.2_build/ghidra_10.1.2_PUBLIC_20220125.zip
  - https://github.com/rizinorg/cutter/releases/download/v2.0.2/Cutter-v2.0.2-x64.Linux.AppImage

pwntool_dependencies:
  - python3
  - python3-pip
  - python3-dev
  - git
  - libssl-dev
  - libffi-dev
  - build-essential

python_bindings:
  - capstone
  - unicorn
  - keystone-engine
  - ropper
  - pwntools
