---
- name: Include vars of pwnlin_vars.yml file.
  include_vars:
    file: pwnlin_vars.yml

- name: Creating Linux Pwn directory in "{{ pwn_lin_dir }}"
  file:
    path: "{{ pwn_lin_dir }}"
    state: directory
    owner: "{{ user_dir }}"
    mode: "0755"
  become: yes

- name: Cloning Linux Focused tools  - Enumeration
  git:
    repo: "{{ item }}"
    dest: "{{ pwn_lin_dir }}/enumeration/{{ item.split('/')[-1].replace('.git','')}}"
    version: master
  with_items: "{{ lin_enum }}"
  become: yes

- name: Cloning Linux Focused tools  - Payload Crafting
  git:
    repo: "{{ item }}"
    dest: "{{ pwn_lin_dir }}/payload_crafting/{{ item.split('/')[-1].replace('.git','')}}"
    version: master
  with_items: "{{ lin_payload }}"
  become: yes

- name: Cloning Linux Focused tools  - Web
  git:
    repo: "{{ item }}"
    dest: "{{ pwn_lin_dir }}/web/{{ item.split('/')[-1].replace('.git','')}}"
    version: master
  with_items: "{{ lin_web }}"
  become: yes

- name: Cloning Linux Focused tools  - Cred Dumping
  git:
    repo: "{{ item }}"
    dest: "{{ pwn_lin_dir }}/cred_dumping/{{ item.split('/')[-1].replace('.git','')}}"
    version: master
  with_items: "{{ lin_cred_dump }}"
  become: yes

- name: Cloning Linux Focused tools  - rootkits
  git:
    repo: "{{ item }}"
    dest: "{{ pwn_lin_dir }}/rootkits/{{ item.split('/')[-1].replace('.git','')}}"
    version: master
  with_items: "{{ lin_rootkits }}"
  become: yes

- name: Downloading precompiled Packages
  get_url:
    url: "{{ item }}"
    dest: "{{ pwn_lin_dir }}"
    mode: 644
    owner: "{{ user_dir }}"
  with_items: "{{ precompiled_packages }}"
  become: yes
